- name: Installing stow
  apt: name=stow
  tags:
    - install
    - dotfiles
    - stow
    - server
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: "https://github.com/ramymain/.dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install
    - dotfiles
    - stow
    - server
- name: Stat .bashrc
  stat: path=$HOME/.bashrc
  register: bashrc_stat
- name: Move .bashrc
  command: mv $HOME/.bashrc $HOME/.bashrc.bak
  when: bashrc_stat.stat.exists
- name: Stat .bash_profile
  stat: path=$HOME/.bash_profile
  register: bash_profile_stat
- name: Move .bash_profile
  command: mv $HOME/.bash_profile $HOME/.bash_profile.bak
  when: bash_profile_stat.stat.exists
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./setup
  tags:
    - install
    - dotfiles
    - stow
    - server